# Generated by Django 4.2 on 2023-04-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='TrainingWay',
        ),
    ]
