# Generated by Django 4.2 on 2023-04-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_mymodel_trainingway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.trainingway')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.test')),
            ],
        ),
    ]
