# Generated by Django 4.2 on 2023-04-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_test_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='answer',
        ),
    ]
