# Generated by Django 4.2 on 2023-04-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_rename_answer_question_right_answer_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingway',
            old_name='requirements',
            new_name='description',
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='training',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.trainingway'),
        ),
    ]
