# Generated by Django 4.2 on 2023-04-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rename_requirements_trainingway_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='training',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingway',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bank.test'),
        ),
    ]
