# Generated by Django 4.2 on 2023-04-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_testresult_answer_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.testresult'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingway',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.test'),
        ),
    ]
