# Generated by Django 4.2 on 2023-04-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_question_detailed_alter_answer_test_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='right_answer',
        ),
    ]
